marks=[94.4, 88.9, 92.5, 85.0, 90.2]
marks.append(98.5)
print(marks)
marks.sort()
print(marks)
marks.sort(reverse=True)
print(marks)
marks.insert(3,44.5)
print(marks)
marks.reverse()
print(marks)
marks.remove(85.0)
print(marks)
marks.pop(2)
print(marks)